# -*- coding: utf-8 -*-
"""Assemble the self-contained v2 DL trainer kernel (.ipynb + metadata).

Cell 0: GPU-arch fix — child-process CUDA smoke test + torch cu124 reinstall
        (the current Kaggle image ships torch without sm_75 kernels; observed
        2026-08-21: all 10 configs died with cudaErrorNoKernelImageForDevice
        on T4).
Cell 1: dl_pipeline.py inlined verbatim.
Cell 2: the v2 trainer body (dl_trainer_v2_source.py).

Kernel ids MUST equal the slug Kaggle derives from the title, or the second
push 409s (learned the hard way).
"""
import io
import json
import sys
from pathlib import Path

import os as _os
import pathlib as _pathlib

# Working directory. Defaults to the results/ tree shipped in this
# repository so the analysis and emit scripts run straight from a checkout;
# set PAPER_V2_DIR to a full working tree (with the parquet splits and
# runs_v2/) to regenerate results from scratch.
_ROOT = _os.environ.get("PAPER_V2_DIR") or str(
    _pathlib.Path(__file__).resolve().parent.parent / "results")

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

V2 = Path(_ROOT)
PIPE = (Path(_ROOT).parent / "dl_pipeline.py") \
    .read_text(encoding="utf-8")
BODY = (V2 / "dl_trainer_v2_source.py").read_text(encoding="utf-8")
# OPS_SECRET_INJECT: substitute the placeholder at build time (secret lives
# in the env file named by DL_DROP_ENV, never in this file or in git)
import io as _io
_sec = [l.split('=',1)[1].strip() for l in _io.open(os.environ.get("DL_DROP_ENV", ""), encoding='utf-8') if l.startswith('REVERT_OPS_SECRET=')][0]
BODY = BODY.replace(chr(60)*2 + chr(79)+chr(80)+chr(83)+chr(95)+chr(83)+chr(69)+chr(67)+chr(82)+chr(69)+chr(84) + chr(62)*2, _sec)

ENVFIX = '''# --- GPU-arch fix ----------------------------------------------------------
# The current Kaggle image ships a torch build without sm_75 kernels, so every
# CUDA op on a T4 dies with cudaErrorNoKernelImageForDevice (observed
# 2026-08-21: 10/10 configs failed). Smoke-test CUDA in a CHILD process (this
# cell must not import torch itself); if the smoke fails, install a cu124
# build that still carries sm_75 - later cells then import the fresh torch.
import subprocess, sys

SMOKE = "import torch; x = torch.zeros(4, device='cuda') + 1; print('smoke-ok', torch.__version__)"
smoke = subprocess.run([sys.executable, "-c", SMOKE],
                       capture_output=True, text=True, timeout=300)
print(smoke.stdout.strip() or smoke.stderr.strip()[-400:])
if "smoke-ok" not in smoke.stdout:
    print("reinstalling torch cu124 (sm_75)...")
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "torch==2.6.0", "--index-url",
                    "https://download.pytorch.org/whl/cu124"], check=True)
    chk = subprocess.run([sys.executable, "-c",
                          SMOKE.replace("smoke-ok", "fixed")],
                         capture_output=True, text=True, timeout=300)
    print(chk.stdout.strip() or chk.stderr.strip()[-400:])
    assert "fixed" in chk.stdout, "torch reinstall did not fix CUDA"
'''

def nb(cells):
    return {"nbformat": 4, "nbformat_minor": 5,
            "metadata": {"kernelspec": {"name": "python3",
                                        "display_name": "Python 3",
                                        "language": "python"}},
            "cells": [{"cell_type": "code", "metadata": {},
                       "execution_count": None, "outputs": [],
                       "source": src.splitlines(keepends=True)}
                      for src in cells]}

# 8.5h budget: the 12h wall killed both first attempts (11h default +
# ~40min load/tokenize/torch-reinstall overhead + config in flight >
# 12h), and cancelled batch kernels persist NOTHING.
BUDGET = "import os; os.environ['DL_TIME_BUDGET_SEC']='30600'\n"
for variant, env in (("fwd", BUDGET),
                     ("rev", BUDGET + "os.environ['REVERSE_ORDER']='1'\n")):
    kdir = V2 / f"kernel_{variant}"
    kdir.mkdir(exist_ok=True)
    cells = [
        ENVFIX,
        "# dl_pipeline.py - inlined verbatim (registry of 10 configs, nested\n"
        "# internal split, atomic run caching). Source of truth lives in the\n"
        "# GitHub repo; this copy is generated by build_kernel_v2.py.\n" + PIPE,
        env + BODY,
    ]
    (kdir / "trainer_v2.ipynb").write_text(
        json.dumps(nb(cells), ensure_ascii=False), encoding="utf-8")
    meta = {
        "id": f"sergeisolovyev/sc-vuln-dl-v2-trainer-{variant}",
        "title": f"SC Vuln DL v2 Trainer {variant.upper()}",
        "code_file": "trainer_v2.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": True,
        "machine_shape": "NvidiaTeslaT4",
        "enable_internet": True,
        "dataset_sources": ["sergeisolovyev/defi-bytecode-features-v2"],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (kdir / "kernel-metadata.json").write_text(json.dumps(meta, indent=2),
                                               encoding="utf-8")
    print("built", kdir.name)
print("ok")
